<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="controlplane" nsURI="http://www.example.org/controlplane" nsPrefix="controlplane">
  <eClassifiers xsi:type="ecore:EClass" name="Actor" eSuperTypes="common.ecore#//DomainElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="specialization" upperBound="-1"
        eType="#//Actor" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Interaction" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Actor"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="behavior" eType="#//InteractionBehavior"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cardinality" eType="#//InteractionCardinality"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isBinding" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActorToActorInteraction" eSuperTypes="#//Interaction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        upperBound="-1" eType="#//Actor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActorToItemTypeIteraction" eSuperTypes="#//Interaction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        upperBound="-1" eType="#//ItemType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ItemType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="typeAttribute" upperBound="-1"
        eType="#//ItemTypeAttribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isA" lowerBound="1" eType="ecore:EClass common.ecore#//DomainSpecificType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subType" upperBound="-1"
        eType="#//ItemType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="InteractionBehavior">
    <eLiterals name="SYNC"/>
    <eLiterals name="ASYNC" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="InteractionCardinality">
    <eLiterals name="ONE_TO_ONE"/>
    <eLiterals name="ONE_TO_MANY" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ItemTypeAttribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ControlPlane" eSuperTypes="metametamodel.ecore#//Plane">
    <eStructuralFeatures xsi:type="ecore:EReference" name="actor" upperBound="-1"
        eType="#//Actor" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="interaction" upperBound="-1"
        eType="#//Interaction" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domainSpecificType" upperBound="-1"
        eType="ecore:EClass common.ecore#//DomainSpecificType" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
