<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dataplane" nsURI="http://www.example.org/dataplane" nsPrefix="dataplane">
  <eClassifiers xsi:type="ecore:EClass" name="Item" eSuperTypes="common.ecore#//DomainElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="risesAs" eType="#//RisingBehavior"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isA" lowerBound="1" eType="ecore:EClass common.ecore#//DomainSpecificType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RisingBehavior">
    <eLiterals name="STATIC"/>
    <eLiterals name="DYNAMIC" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Relationship" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Item"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Inheritance" eSuperTypes="#//Relationship">
    <eStructuralFeatures xsi:type="ecore:EReference" name="item" lowerBound="1" eType="#//Item"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Composition" eSuperTypes="#//Relationship">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        upperBound="-1" eType="#//Item"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataPlane" eSuperTypes="metametamodel.ecore#//Plane">
    <eStructuralFeatures xsi:type="ecore:EReference" name="item" upperBound="-1" eType="#//Item"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="itemRelationship" upperBound="-1"
        eType="#//Relationship" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
